mysite/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name='index'),
    path('eboard/', views.eboard, name='eboard'),
    path('events/', views.events, name='events'),
    path('contact/', views.contact, name='contact'),
    path('contact-view/', views.contact_view, name='contact_view'),
    path('resources/', views.resources, name='resources'),
    path('lectures/', views.lectures, name='lectures'),
    path('workshops/', views.workshops, name='workshops'),
]

mysite/mysite/urls.py
from django.contrib import admin
from myapp import views
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),  # Ensure myapp URLs are included
]

mysite/myapp/models.py
from django.db import models

# Create your models here.

mysite/myapp/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, required=True)
    subject = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

mysite/myapp/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.http import HttpResponse
from .forms import ContactForm

# Create your views here.
def index(request):
    form = ContactForm()
    return render(request, 'myapp/index.html', {'form': form})

def eboard(request):
    form = ContactForm()
    return render(request, 'myapp/eboard.html', {'form': form})

def events(request):
    form = ContactForm()
    return render(request, 'myapp/events.html', {'form': form})

def contact(request):
    form = ContactForm()
    return render(request, 'myapp/contact.html', {'form': form})

def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            subject = form.cleaned_data['subject']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            
            email_message = f'Name: {name}\nSubject: {subject}\nEmail: {email}\nMessage: {message}'

            send_mail(subject, email_message, email, ['migofbostoncollege@gmail.com'])
            return redirect('index')
        else:
            return HttpResponse('Invalid form')
    else:
        form = ContactForm()
    return render(request, 'myapp/contact.html', {'form': form})




def lectures(request):
    form = ContactForm()
    return render(request, 'myapp/lectures.html', {'form': form})

def resources(request):
    return render(request, 'myapp/resources.html')

def workshops(request):
    form = ContactForm()
    return render(request, 'myapp/workshops.html', {'form': form})

mysite/myapp/templates/myapp/contact.html
<!-- contact.html -->

<div class="contact">
    <h2>Interested?</h2>
    <p style="width: 700px;">Join a community of innovators exploring the limitless possibilities of AI and machine learning. Discover, learn, and make an impact with us.</p>

    <form method="POST" action="{% url 'contact_view' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">Name</label>
            {{ form.name|default:"John Doe" }}
        </div>

        <div class="form-group">
            <label for="id_subject">Subject</label>
            {{ form.subject|default:"General Inquiry" }}
        </div>

        <div class="form-group">
            <label for="id_email">Email</label>
            {{ form.email|default:"example@example.com" }}
        </div>

        <div class="form-group">
            <label for="id_message">Message</label>
            {{ form.message|default:"" }}
        </div>
        <button type="submit">Send Message</button>
    </form>

    <a class="join_bc" href="https://discord.gg/gnuFjMQfgD" target="_blank">BC Student? Click here.</a>
</div>

mysite/myapp/templates/myapp/eboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Boston College Machine Intelligence Group</title>
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>

    <!-- Navigation Bar -->
    <nav>
        <div class = "nav-container">
        <a href="{% url 'index' %}">
            <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
        </a>
            <a href="{% url 'eboard' %}">Meet the Board</a>
            <a href="{% url 'events' %}">Calendar</a>
            
            <div class="dropdown">
                <button class="dropbtn">Our Programs</button>
                <div class="dropdown-content">
                    <a href="{% url 'lectures' %}">Lectures</a>
                <a href="{% url 'workshops' %}">Workshops</a>
                <a href="{% url 'resources' %}">Resources</a>
                </div>
                <a href="https://discord.gg/gnuFjMQfgD" target="_blank">Join</a>
            </div>
        </div>
    </nav>

   <!-- Executive Board Section-->
    <div class="eboard">
        <h2 style="margin-top: 120px;">Meet the Board</h2>
        <p style="margin-top: -20px;">Put a face to the name!</p>
        <div class="board">
            <div class="board-member">
                <img src="{% static 'images/jason.jpg' %}" class="board-image">
                <h3>President</h3>
                <p>Jason Adhinarta</p>
                <a href="https://www.linkedin.com/in/jason-adhinarta/" target="_blank"><img src="{% static 'images/linkedin.png' %}" class="linkedin"></a>
            </div>
            <div class="board-member">
                <img src="{% static 'images/steve.jpg' %}" class="board-image">
                <h3>President</h3>
                <p>Steve Roche</p>
                <a href="https://www.linkedin.com/in/steven-roche-a7a16b22b/" target="_blank"><img src="{% static 'images/linkedin.png' %}" class="linkedin"></a>
            </div>
            <div class="board-member">
                <img src="{% static 'images/xander.jpg' %}" class="board-image">
                <h3>Vice President, Treasurer</h3>
                <p>Xander Widener</p>
                <a href="https://www.linkedin.com/in/m-xander-widener/" target="_blank"><img src="{% static 'images/linkedin.png' %}" class="linkedin"></a>
            </div>
            <div class="board-member">
                <img src="{% static 'images/josh.jpg' %}" class="board-image">
                <h3>Event Coordinator</h3>
                <p>Joshua Gorniak</p>
                <a href="https://www.linkedin.com/in/joshua-gorniak/" target="_blank"><img src="{% static 'images/linkedin.png' %}" class="linkedin"></a>
            </div>
            <div class="board-member">
                <img src="{% static 'images/talia.png' %}" class="board-image">
                <h3>Lead Software Developer</h3>
                <p>Talia Kusmirek</p>
                <a href="https://www.linkedin.com/in/talia-kusmirek-b0421b289/" target="_blank"><img src="{% static 'images/linkedin.png' %}" class="linkedin"></a>
            </div>
            <div class="board-member">
                <img src="{% static 'images/michael.jpg' %}" class="board-image">
                <h3>Director of Marketing</h3>
                <p>Michael Lin</p>
                <a href="https://www.linkedin.com/in/michael-lin-b70048225/" target="_blank"><img src="{% static 'images/linkedin.png' %}" class="linkedin"></a>
            </div>
            <div class="board-member">
                <img src="{% static 'images/emma.jpg' %}" class="board-image">
                <h3>Director of Outreach</h3>
                <p>Emma Su</p>
                <a href="https://www.linkedin.com/in/emmmasu/" target="_blank"><img src="{% static 'images/linkedin.png' %}" class="linkedin"></a>
            </div>
        </div>
    </div>



    <!-- Explore Section -->
    <div class="explore_tab">
        <h3>Explore our</h3>
        <a href="{% url 'lectures' %}">Lectures</a>
        <a href="{% url 'workshops' %}">Workshops</a>
        <a href="{% url 'resources' %}">Resources</a>
    </div>

    <!-- Call to Action (Discord Join) -->
    {% include 'myapp/contact.html' %}

    <div class = "footer">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="footer_logo">

        <div class="footer-links">
            <a href="{% url 'index' %}">Home</a>
            <a href="{% url 'eboard' %}">Meet the Board</a>
            <a href="{% url 'lectures' %}">Lectures</a>
            <a href="{% url 'workshops' %}">Workshops</a>
            <a href="{% url 'events' %}">Calendar</a>
            <a href="{% url 'resources' %}">Resources</a>
        </div>
        <div class="footer-links" style="margin-top: 20px;">
            <a href="https://instagram.com/migbostoncollege" target="_blank"><img src="{% static 'images/instagram.png' %}" class="linkedin"></a>
            <a href="https://www.youtube.com/@migofbc" target="_blank"><img src="{% static 'images/youtube.png' %}" class="linkedin"></a>
        </div>
        <p style="font-size: 8px;">&copy; 2024 Boston College Machine Learning Group</p>
    </div>







    <script>
        function toggleAnswer(questionElement) {
            const faq = questionElement.parentElement;
            faq.classList.toggle('active');
            if (faq.classList.contains('active')) {
                faq.style.animation = 'bubblyJump 0.5s ease-in-out';
            } else {
                faq.style.animation = '';
            }
        }

        window.onscroll = function() {
    const nav = document.querySelector('nav');
    if (window.pageYOffset > 0) {
        nav.classList.add('sticky');
    } else {
        nav.classList.remove('sticky');
    }
};
    </script>
    <style>
        @keyframes bubblyJump {
            0% {
                transform: translateY(0);
            }
            50% {
                transform: translateY(-10px);
            }
            100% {
                transform: translateY(0);
            }
        }
    </style>
</body>





</html>

mysite/myapp/templates/myapp/events.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Boston College Machine Intelligence Group</title>
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>

    <!-- Navigation Bar -->
    <nav>
        <div class = "nav-container">
        <a href="{% url 'index' %}">
            <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
        </a>
            <a href="{% url 'eboard' %}">Meet the Board</a>
            <a href="{% url 'events' %}">Calendar</a>
            
            <div class="dropdown">
                <button class="dropbtn">Our Programs</button>
                <div class="dropdown-content">
                    <a href="{% url 'lectures' %}">Lectures</a>
                <a href="{% url 'workshops' %}">Workshops</a>
                <a href="{% url 'resources' %}">Resources</a>
                </div>
                <a href="https://discord.gg/gnuFjMQfgD" target="_blank">Join</a>
            </div>
        </div>
    </nav>

    <!-- Google Calendar Events Section -->
    <div class="events">
        <!-- Google Calendar Events Section -->
        <div class="events" style="margin-top: 50px; text-align: center;">
            <iframe src="https://calendar.google.com/calendar/embed?src=0cab6de18d3d4a4f68f61c63cce02fa128cf65c4ad06bf17d455287d65b38dd8%40group.calendar.google.com&ctz=America%2FNew_York&showTitle=false" style="border: 20px" width="800" height="600" frameborder="0" scrolling="no"></iframe>
        </div>
    </div>



    <!-- Explore Section -->
    <div class="explore_tab">
        <h3>Explore our</h3>
        <a href="{% url 'lectures' %}">Lectures</a>
        <a href="{% url 'workshops' %}">Workshops</a>
        <a href="{% url 'resources' %}">Resources</a>
    </div>

    <!-- Call to Action (Discord Join) -->
    <!-- IMPLEMENT EMAIL SENT -->
    {% include 'myapp/contact.html' %}

    <div class = "footer">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="footer_logo">

        <div class="footer-links">
            <a href="{% url 'index' %}">Home</a>
            <a href="{% url 'eboard' %}">Meet the Board</a>
            <a href="{% url 'lectures' %}">Lectures</a>
            <a href="{% url 'workshops' %}">Workshops</a>
            <a href="{% url 'events' %}">Calendar</a>
            <a href="{% url 'resources' %}">Resources</a>
        </div>
        <div class="footer-links" style="margin-top: 20px;">
            <a href="https://instagram.com/migbostoncollege" target="_blank"><img src="{% static 'images/instagram.png' %}" class="linkedin"></a>
            <a href="https://www.youtube.com/@migofbc" target="_blank"><img src="{% static 'images/youtube.png' %}" class="linkedin"></a>
        </div>
        <p style="font-size: 8px;">&copy; 2024 Boston College Machine Learning Group</p>
    </div>







    <script>
        function toggleAnswer(questionElement) {
            const faq = questionElement.parentElement;
            faq.classList.toggle('active');
            if (faq.classList.contains('active')) {
                faq.style.animation = 'bubblyJump 0.5s ease-in-out';
            } else {
                faq.style.animation = '';
            }
        }

        window.onscroll = function() {
    const nav = document.querySelector('nav');
    if (window.pageYOffset > 0) {
        nav.classList.add('sticky');
    } else {
        nav.classList.remove('sticky');
    }
};
    </script>
    <style>
        @keyframes bubblyJump {
            0% {
                transform: translateY(0);
            }
            50% {
                transform: translateY(-10px);
            }
            100% {
                transform: translateY(0);
            }
        }
    </style>
</body>

</html>

mysite/myapp/templates/myapp/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Boston College Machine Intelligence Group</title>
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>

    <!-- Navigation Bar -->
    <nav>
        <div class = "nav-container">
        <a href="{% url 'index' %}">
            <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
        </a>
            <a href="{% url 'eboard' %}">Meet the Board</a>
            <a href="{% url 'events' %}">Calendar</a>
            
            <div class="dropdown">
                <button class="dropbtn">Our Programs</button>
                <div class="dropdown-content">
                    <a href="{% url 'lectures' %}">Lectures</a>
                <a href="{% url 'workshops' %}">Workshops</a>
                <a href="{% url 'resources' %}">Resources</a>
                </div>
                <a href="https://discord.gg/gnuFjMQfgD" target="_blank">Join</a>
            </div>
        </div>
    </nav>

    <!-- Hero Section -->
    <div class="hero-section">
        <img src="{% static 'images/landingimage.png' %}" class="landingimage" alt="Landing Image">
        <h1 style="flex: 1; width: 400px; text-align: left; margin-left: 2.5em; position: absolute; top: 50%; transform: translateY(-50%);">
            Students at the forefront of shaping AI's future.
        </h1>
    </div>

    <!-- Mission Section -->
    <div class="about">
        <div style="display: flex; align-items: center;">
            <div style="margin-left: 4.5em;">
                <h2>Our Mission</h2>
                <p>
                    The Boston College Machine Learning Group is a hub of highly motivated undergraduate students committed to 
                    advancing the field of machine learning. <br><br> Our mission is to develop, explore, and apply machine learning techniques 
                    to solve real-world problems and to promote knowledge and skills in AI through workshops, guest lectures, and hands-on projects.
                </p>
            </div>

            <div class="faqs">
                <div class="faq">
                    <h3 class="faq-question" onclick="toggleAnswer(this)">I don't know anything about AI or programming. Should I still join?</h3>
                    <p class="faq-answer">Yes! The first MIG lecture each year is a crash course in machine learning and following lectures are approachable to a general audience. As the year goes on, we will dive into increasingly complex topics, but we also strive to provide a space to ask any questions no matter how rudimentary. Alongside the resources we share during meetings, our <a href="{% url 'resources' %}">resource page</a> is perfect for a beginner to hone their understanding and comfort with overtime.</p>
                </div>
                <div class="faq">
                    <h3 class="faq-question" onclick="toggleAnswer(this)">Could MIG help me get involved with research?</h3>
                    <p class="faq-answer">Yes! The eboard and your fellow club members have connections in the BC research community and beyond. Just ask!</p>
                </div>
                <div class="faq">
                    <h3 class="faq-question" onclick="toggleAnswer(this)">Can I give a talk at MIG?</h3>
                    <p class="faq-answer">Anyone in MIG can volunteer to give a talk at our weekly meetings. Talks typically run ~30 minutes and are supplemented with a slide show (and the occasional notebook). All talks are recorded and posted on the YouTube channel. <a href="https://docs.google.com/forms/d/e/1FAIpQLScuDHEgixUnMaW-bwqBrtfizlqwlcCCHiPigEp3Cd8IAubJIg/viewform" target="_blank">Signing up to give a talk</a> implies consent to be recorded. If you have any questions or concerns, please reach out to an eboard member.</p>
                </div>
            </div>
            
        </div>
    </div>





    <!-- Recent Work Section -->
    <div class="recent">
        <h2 style="margin-left: 2.2em;">Recent Events</h2>
        <div style="display: flex; justify-content: center;">
            <!-- Most recent event -->
            <div class="event" style="margin-left: .6em;">
                <img src="{% static 'images/supervised_learning.png' %}" class="eventimage" alt="Supervised Learning Image">
                <p class="date">October 21, 2024</p>
                <a class="lecture_link" href="https://www.youtube.com/watch?v=Htoq6A4Fb6U" target="_blank">
                <h3>Basics of Supervised Learning</h3>
                <p>Talia Kusmirek presents the basics of supervised learning and types of algorithm within each of its subrealms.</p>
            </div>
    
            <!-- Second most recent event -->
            <div class="event" style="margin-right: .0em;">
                <img src="{% static 'images/matthew.png' %}" class="eventimage" alt="Guest Lecture Image">
                <p class="date">October 7, 2024</p>
                <a class="lecture_link" href="https://www.youtube.com/watch?v=Gb4J4X2lvUM" target="_blank">
                <h3>RNNs and Test-Time Training</h3>
                <p>MIG member Matthew Eichelman discusses Recurrent Neural Networks and ways to test-time train with them!</p>
            </div>
    
            <!-- Third most recent event -->
            <div class="event">
                <img src="{% static 'images/joshlecture.png' %}" class="eventimage" alt="Workshop Image">
                <p class="date">September 23, 2024</p>
                <a class="lecture_link" href="https://www.youtube.com/watch?v=tzkl9OELL64&t=1s" target="_blank">
                <h3>What is Synthetic Signature Generation?</h3>
                <p class="event_info">Josh Gorniak discusses his summer research on signatures.</p>
            </div>
        </div>
    </div>
    

    <!-- Explore Section -->
    <div class="explore_tab">
        <h3>Explore our</h3>
        <a href="{% url 'lectures' %}">Lectures</a>
        <a href="{% url 'workshops' %}">Workshops</a>
        <a href="{% url 'resources' %}">Resources</a>
    </div>

    <!-- Call to Action (Discord Join) -->
    <!-- IMPLEMENT EMAIL SENT -->
    {% include 'myapp/contact.html' %}

    <div class = "footer">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="footer_logo">

        <div class="footer-links">
            <a href="{% url 'index' %}">Home</a>
            <a href="{% url 'eboard' %}">Meet the Board</a>
            <a href="{% url 'lectures' %}">Lectures</a>
            <a href="{% url 'workshops' %}">Workshops</a>
            <a href="{% url 'events' %}">Calendar</a>
            <a href="{% url 'resources' %}">Resources</a>
        </div>
        <div class="footer-links" style="margin-top: 20px;">
            <a href="https://instagram.com/migbostoncollege" target="_blank"><img src="{% static 'images/instagram.png' %}" class="linkedin"></a>
            <a href="https://www.youtube.com/@migofbc" target="_blank"><img src="{% static 'images/youtube.png' %}" class="linkedin"></a>
        </div>
        <p style="font-size: 8px;">&copy; 2024 Boston College Machine Learning Group</p>
    </div>







    <script>
        function toggleAnswer(questionElement) {
            const faq = questionElement.parentElement;
            faq.classList.toggle('active');
            if (faq.classList.contains('active')) {
                faq.style.animation = 'bubblyJump 0.5s ease-in-out';
            } else {
                faq.style.animation = '';
            }
        }

        window.onscroll = function() {
    const nav = document.querySelector('nav');
    if (window.pageYOffset > 0) {
        nav.classList.add('sticky');
    } else {
        nav.classList.remove('sticky');
    }
};
    </script>
    <style>
        @keyframes bubblyJump {
            0% {
                transform: translateY(0);
            }
            50% {
                transform: translateY(-10px);
            }
            100% {
                transform: translateY(0);
            }
        }
    </style>
</body>





</html>

mysite/myapp/templates/myapp/lectures.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Boston College Machine Intelligence Group</title>
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>

    <!-- Navigation Bar -->
    <nav>
        <div class = "nav-container">
        <a href="{% url 'index' %}">
            <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo">
        </a>
            <a href="{% url 'eboard' %}">Meet the Board</a>
            <a href="{% url 'events' %}">Calendar</a>
            
            <div class="dropdown">
                <button class="dropbtn">Our Programs</button>
                <div class="dropdown-content">
                    <a href="{% url 'lectures' %}">Lectures</a>
                <a href="{% url 'workshops' %}">Workshops</a>
                <a href="{% url 'resources' %}">Resources</a>
                </div>
                <a href="https://discord.gg/gnuFjMQfgD" target="_blank">Join</a>
            </div>
        </div>
    </nav>

    <!-- Lectures Section -->
    <div class="recent">
        <h2 style="text-align: center; margin-top:-40px;">Our Lectures</h2>
        <div style="display: flex; align-items: center; justify-content: center;">
            <div class="event"  style="margin-left: .6em;">
                <img src="{% static 'images/supervised_learning.png' %}" class="eventimage" alt="Supervised Learning Image">
                <p class="date">October 21, 2024</p>
                <a class="lecture_link" href="https://www.youtube.com/watch?v=Htoq6A4Fb6U" target="_blank">
                <h3>Basics of Supervised Learning</h3>
                <p>Talia Kusmirek presents the basics of supervised learning and types of algorithm within each of its subrealms.</p>
            </div>
            <div class="event" style="margin-right: .0em;">
                <img src="{% static 'images/matthew.png' %}" class="eventimage" alt="Guest Lecture Image">
                <p class="date">October 7, 2024</p>
                <a class="lecture_link" href="https://www.youtube.com/watch?v=Gb4J4X2lvUM" target="_blank">
                <h3>RNNs and Test-Time Training</h3>
                <p>MIG member Matthew Eichelman discusses Recurrent Neural Networks and ways to test-time train with them!</p>
            </div>
            <div class="event" >
                <img src="{% static 'images/workshop1.png' %}" class="eventimage" alt="Guest Lecture Image">
                <p class="date">September 23, 2024</p>
                <a class="lecture_link" href="https://www.youtube.com/watch?v=tzkl9OELL64&t=1s" target="_blank">
                    <h3>Synthetic Signature Generation</h3>
                </a>
                <p>Josh Gorniak discusses his summer research on signatures.</p>
            </div>
        </div>
    </div>




    <!-- Explore Section -->
    <div class="explore_tab">
        <h3>Explore our</h3>
        <a href="{% url 'lectures' %}">Lectures</a>
        <a href="{% url 'workshops' %}">Workshops</a>
        <a href="{% url 'resources' %}">Resources</a>
    </div>

    <!-- Call to Action (Discord Join) -->
    <!-- IMPLEMENT EMAIL SENT -->
    {% include 'myapp/contact.html' %}

    <div class = "footer">
        <img src="{% static 'images/logo.png' %}" alt="Logo" class="footer_logo">

        <div class="footer-links">
            <a href="{% url 'index' %}">Home</a>
            <a href="{% url 'eboard' %}">Meet the Board</a>
            <a href="{% url 'lectures' %}">Lectures</a>
            <a href="{% url 'workshops' %}">Workshops</a>
            <a href="{% url 'events' %}">Calendar</a>
            <a href="{% url 'resources' %}">Resources</a>
        </div>
        <div class="footer-links" style="margin-top: 20px;">
            <a href="https://instagram.com/migbostoncollege" target="_blank"><img src="{% static 'images/instagram.png' %}" class="linkedin"></a>
            <a href="https://www.youtube.com/@migofbc" target="_blank"><img src="{% static 'images/youtube.png' %}" class="linkedin"></a>
        </div>
        <p style="font-size: 8px;">&copy; 2024 Boston College Machine Learning Group</p>
    </div>







    <script>
        function toggleAnswer(questionElement) {
            const faq = questionElement.parentElement;
            faq.classList.toggle('active');
            if (faq.classList.contains('active')) {
                faq.style.animation = 'bubblyJump 0.5s ease-in-out';
            } else {
                faq.style.animation = '';
            }
        }

        window.onscroll = function() {
    const nav = document.querySelector('nav');
    if (window.pageYOffset > 0) {
        nav.classList.add('sticky');
    } else {
        nav.classList.remove('sticky');
    }
};
    </script>
    <style>
        @keyframes bubblyJump {
            0% {
                transform: translateY(0);
            }
            50% {
                transform: translateY(-10px);
            }
            100% {
                transform: translateY(0);
            }
        }
    </style>
</body>

</html>